version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:10'
    working_directory: ~/repo
    
    steps:
      - checkout
      - run:
          name: 'Setting project 1'
          command: 'npm install'
      - run:
          name: 'build project 1'
          command: 'npm run build'
      - run:
          name: 'Setting ws xhr2 bufferutil utf-8-validate'
          command: 'npm install ws xhr2 bufferutil utf-8-validate  -D'
      - run: 
          name: 'install and build function'
          command: 'cd functions && npm install && npm run build'
      - run:
          name: 'Build Project'
          command: 'npm run build:ssr'
      - run: 
          name: 'install firebase tools'
          command: npm install firebase-tools
      - run:
          name: 'Deploy to Firebase Hosting'
          command: './node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN'
