version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:12'
    working_directory: ~/repo
    
    steps:
      - checkout
      - run: 
          name: 'install function'
          command: cd functions && npm instal
      - run:
          name: 'Setting env'
          command: 'npm install'
      - run:
          name: 'Setting env'
          command: 'npm run build'
      - run:
          name: 'Setting env'
          command: 'npm install ws xhr2 bufferutil utf-8-validate  -D'
      - run:
          name: 'Build Project'
          working_directory: ./functions
          command: 'npm run build:ssr'
      - run:
          name: 'Deploy to Firebase Hosting'
          working_directory: ./functions
          command: './node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN'